# Generated by Django 2.2.3 on 2019-07-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
